apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:   # Agrega la referencia a Docker Hub
      - name: dockerhub-secret  
      containers:
      - name: backend
        image: albert1w22/backend-image:latest   # Asegúrate de poner tu usuario correcto
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
